<a href="https://colab.research.google.com/github/atulcoin/Simple-Face-Recognition-/blob/master/final_face_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pafy
!pip install imutils pafy youtube-dl

In [50]:
import imutils
import cv2
import pafy
import youtube_dl
from google.colab.patches import cv2_imshow

In [51]:
url = "https://www.youtube.com/watch?v=hoNb6HuNmU0"
vPafy = pafy.new(url)

play = vPafy.getbest(preftype="mp4")

In [ ]:
cap = cv2.VideoCapture(play.url)
print(cap.isOpened()) # if in cap we have entered wrong file path then it will give false else true
while(cap.isOpened()):    # TO CAPTURE FRAMES OF CAMERA TO VIEW AS VIDEO 
  #  print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) # TO PRINT HEIGHT or property OF THE FRAME 
  #  print(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) # TO PRINT WIDTHE OF THE FRAME 
    face_dec = cv2.CascadeClassifier("haarcascade_frontalface_default.xml")

    ret, frame= cap.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) # here i am printing gray image as output
    faces = face_dec.detectMultiScale(gray, scaleFactor =1.05, minNeighbors=5)

    for x,y,w,h in faces:
        gray = cv2.rectangle(gray, (x,y), (x+w,y+h), (0,255,0),2)
        cv2_imshow(gray)
    if cv2.waitKey(1) == 13:  #13 is the asci code of enter key
        break
cap.release()
cv2.destroyAllWindows()

training of model with custom data set
**bold text**

In [52]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [53]:
from PIL import Image
import os
import numpy as np

bpath = '/content/drive/My Drive/part1face'
image_dir = os.path.join(bpath, "train")

In [54]:
y_label = []
x_train = []

#count = 0

current_id=0
label_id={}


for root, dirs, files in os.walk(image_dir):
  for file in files:
    if file.endswith("png") or file.endswith("jpg"):
      label = os.path.basename(root).replace(" ","-").lower() #we can replace os.path.dirname(path) with root also
      path = os.path.join(root,file)
            #print(label,path)
            
      if not label in label_id:
        label_id[label] = current_id
        current_id +=1
      id_= label_id[label]
      print(id_)
        #img = cv2.imread(path, 1)
      pil_image=  Image.open(path).convert("L") # L to convert image in grey pil image is used to tell sysetem that the file in location is image file
      image_arra=  np.array(pil_image,"uint8")
            #print(image_arra)
            
      y_label.append(id_)
      x_train.append(image_arra)
y_label = np.asarray(y_label, dtype=np.int32)
x_train = np.asarray(x_train, dtype=np.int32)
#model = cv2.face.LBPHFaceRecognizer_create()

#model.train(np.asarray(x_train), np.asarray(y_label))
#with open("labels.pickle", 'wb') as f:
   # pickle.dump(label_id, f)
print("train complete")
print(x_train)
#model.save('save_face.xml')


0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
5
train complete
[[[ 23  23  23 ... 237 234 232]
  [ 22  22  23 ... 236 234 233]
  [ 21  21  22 ... 236 236 237]
  ...
  [252 252 251 ... 115 146 177]
  [252 251 252 ...  95 119 142]
  [251 251 252 ...  82 101 

In [55]:
x_train.shape

(396, 200, 200)

In [56]:
len(x_train)

396

In [57]:
x_train = np.array(x_train)

In [58]:
x_train.shape

(396, 200, 200)

In [59]:
x_train = x_train.astype('float32')
#y_label =y_label.astype('float32')

In [60]:
x_train.shape

(396, 200, 200)

In [61]:
x_train.ndim

3

In [62]:
x_train = np.expand_dims(x_train, -1)

In [63]:
x_train.ndim

4

In [64]:
x_train /= 255
#y_label /=255

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Dropout, Flatten, MaxPooling2D
import keras

creating validation data set for validating

In [65]:
bpath = '/content/drive/My Drive/part1face'
image_dir = os.path.join(bpath, "validation")

In [66]:
y_vali = []
x_vali = []

#count = 0

current_id=0
label_id={}


for root, dirs, files in os.walk(image_dir):
  for file in files:
    if file.endswith("png") or file.endswith("jpg"):
      label = os.path.basename(root).replace(" ","-").lower() #we can replace os.path.dirname(path) with root also
      path = os.path.join(root,file)
            #print(label,path)
            
      if not label in label_id:
        label_id[label] = current_id
        current_id +=1
      id_= label_id[label]
      print(id_)
        #img = cv2.imread(path, 1)
      pil_image=  Image.open(path).convert("L") # L to convert image in grey pil image is used to tell sysetem that the file in location is image file
      image_arra=  np.array(pil_image,"uint8")
            #print(image_arra)
            
      y_vali.append(id_)
      x_vali.append(image_arra)
y_vali = np.asarray(y_vali, dtype=np.int32)
x_vali = np.asarray(x_vali, dtype=np.int32)
#model = cv2.face.LBPHFaceRecognizer_create()

#model.train(np.asarray(x_train), np.asarray(y_label))
#with open("labels.pickle", 'wb') as f:
   # pickle.dump(label_id, f)
print("validation data complete")
print(x_vali)
#model.save('save_face.xml')


0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
4
4
4
4
4
4
4
4
4
4
4
4
5
5
5
5
5
5
5
5
5
5
5
5
validation data complete
[[[128 133 139 ... 105 112 111]
  [127 132 138 ... 105 109 109]
  [128 132 138 ...  99 104 106]
  ...
  [ 55  59  68 ...  38  37  37]
  [ 57  60  70 ...  38  38  38]
  [ 58  61  70 ...  39  38  38]]

 [[ 26  26  26 ...  22  22  22]
  [ 26  25  25 ...  22  22  22]
  [ 26  25  25 ...  22  22  22]
  ...
  [ 18  18  18 ...  17  17  17]
  [ 17  17  17 ...  18  18  17]
  [ 17  17  17 ...  19  18  18]]

 [[136 138 134 ... 129 111 101]
  [134 137 137 ... 140 121 110]
  [133 137 138 ... 162 142 131]
  ...
  [ 56  56  55 ...  40  40  40]
  [ 61  60  59 ...  40  40  40]
  [ 65  64  62 ...  40  40  40]]

 ...

 [[ 29  29  29 ...  97  97  97]
  [ 29  29  29 ...  97  97  97]
  [ 29  29  29 ...  97  97  97]
  ...
  [117 117 117 ... 147 147 147]
  [117 118 117 ... 147 147 147]
  [118 118 117 ... 147 147 147]]

 [[ 72  73  73 ... 148 14

In [67]:
x_vali = x_vali.astype('float32')
#y_vali =y_vali.astype('float32')

In [68]:
x_vali = np.expand_dims(x_vali, -1)

In [69]:
x_vali /= 255
#y_vali /=255

In [ ]:
import tensorflow as tf


In [ ]:
x_train.shape

(72, 200, 200)

In [70]:
x_train[0]

array([[[0.09019608],
        [0.09019608],
        [0.09019608],
        ...,
        [0.92941177],
        [0.91764706],
        [0.9098039 ]],

       [[0.08627451],
        [0.08627451],
        [0.09019608],
        ...,
        [0.9254902 ],
        [0.91764706],
        [0.9137255 ]],

       [[0.08235294],
        [0.08235294],
        [0.08627451],
        ...,
        [0.9254902 ],
        [0.9254902 ],
        [0.92941177]],

       ...,

       [[0.9882353 ],
        [0.9882353 ],
        [0.9843137 ],
        ...,
        [0.4509804 ],
        [0.57254905],
        [0.69411767]],

       [[0.9882353 ],
        [0.9843137 ],
        [0.9882353 ],
        ...,
        [0.37254903],
        [0.46666667],
        [0.5568628 ]],

       [[0.9843137 ],
        [0.9843137 ],
        [0.9882353 ],
        ...,
        [0.32156864],
        [0.39607844],
        [0.42352942]]], dtype=float32)

In [ ]:
y_label[45]

3

In [ ]:
x_vali.shape

(72, 200, 200)

In [71]:
model = keras.models.Sequential([
                         keras.layers.Conv2D(filters=32, kernel_size=3, strides=(1,1), padding='valid', activation='relu', input_shape=[200,200,1]),
                         keras.layers.MaxPool2D(pool_size=(2,2)),
                         keras.layers.Flatten(),
                         keras.layers.Dense(units=128, activation='relu'),
                         keras.layers.Dense(units=10, activation='softmax'),
])

In [72]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

In [73]:
model.fit(x_train, y_label, epochs=10, batch_size=100, validation_data=(x_vali, y_vali), verbose =1)
print ("training complete")

Epoch 1/10
4/4 [==============================] - 7s 2s/step - loss: 16.8045 - accuracy: 0.1616 - val_loss: 17.8404 - val_accuracy: 0.1806
Epoch 2/10
4/4 [==============================] - 11s 3s/step - loss: 12.1472 - accuracy: 0.2247 - val_loss: 16.9366 - val_accuracy: 0.1944
Epoch 3/10
4/4 [==============================] - 7s 2s/step - loss: 4.6613 - accuracy: 0.6843 - val_loss: 12.6491 - val_accuracy: 0.1667
Epoch 4/10
4/4 [==============================] - 7s 2s/step - loss: 0.8996 - accuracy: 0.8157 - val_loss: 14.2268 - val_accuracy: 0.3472
Epoch 5/10
4/4 [==============================] - 7s 2s/step - loss: 0.8117 - accuracy: 0.8510 - val_loss: 12.5808 - val_accuracy: 0.2917
Epoch 6/10
4/4 [==============================] - 7s 2s/step - loss: 0.1640 - accuracy: 0.9394 - val_loss: 12.6049 - val_accuracy: 0.1667
Epoch 7/10
4/4 [==============================] - 7s 2s/step - loss: 0.0686 - accuracy: 0.9697 - val_loss: 12.8940 - val_accuracy: 0.1667
Epoch 8/10
4/4 [===============